export const quickLinks = [
    { name: "Find Doctors", path: "/find-doctor/" },
    { name: "Request Second Opinion", path: "/surgery-care/" },
    { name: "Health Checkup", path: "/health-package/" },
    { name: "Contact Us", path: "/contact-us/" },
];

export const dropdowns = {
    about: [
        "Chairman’s Message",
        "Overview",
        "Board of Directors",
        "Management",
        "International Patient",
        "Why Choose Us",
        "Contact Us",
        "FAQ’s",
    ],
    specialties: [
        { name: "Cardiology", path: "/specialities/cardiac-sciences" },
        { name: "Gastroenterology", path: "/specialities/gastro-sciences" },
        { name: "Neurology", path: "/specialities/neuro-sciences" },
        { name: "Robotics", path: "/specialities/robotics-science" },
        { name: "Transplant", path: "/specialities/transplant-medicine" },
        { name: "Nephrology", path: "/specialities/nephrology" },
        { name: "Urology", path: "/specialities/urology" },
        { name: "Orthopaedics", path: "/specialities/orthopaedics" },
        { name: "Mother & Child Care", path: "/specialities/mother-child-care" },
        { name: "Oncology", path: "/specialities/oncology" },
        { name: "Internal Medicine", path: "/specialities/internal-medicine" },
        { name: "Pulmonology", path: "/specialities/pulmonology" },
        { name: "ENT", path: "/specialities/ent" },
        { name: "Skin & Cosmetic care", path: "/specialities/dermatology-cosmetic-care" },
        { name: "Dental & Maxillofacial", path: "/specialities/dental-and-maxillofacial-care" },
        { name: "Endocrinology", path: "/specialities/endocrinology" },
        { name: "EYE/ Ophthalmology", path: "/specialities/eye-ophthalmology" },
        { name: "Anaesthesia & Pain management", path: "/specialities/anaesthesia-and-pain-management" },
        { name: "Rheumatology", path: "/specialities/rheumatology" }
    ],
    library: [
        { name: "Health Conditions", path: "" },
        { name: "Treatments & Procedures", path: "" },
        { name: "Diagnostics Guide", path: "" },
        { name: "Medicine Guide", path: "" },
        { name: "Symptoms Guide", path: "" },
        { name: "Medical Technology", path: "" },
        { name: "Second Opinion", path: "/surgery-care" },
        { name: "Health Packages", path: "/health-package" },
        { name: "News & Media", path: "" },
    ],
};

export const managementNames = [
    "Dr. Ghantasala Navaneeth",
    "L Panduranga Reddy",
    "Dr. Srikanth Vodnala",
    "Navya Vani S",
    "Dr. Asna Zain",
];

export const directorsNames = [
    "Dr. Keerthikar Reddy",
    "Dr. Deepak Raju",
    "Mr. Raveendra Reddy Rami"
]

export const locations = [
    { name: "Uppal", path: "/contact-us/uppal/" },
    { name: "Kachiguda", path: "/contact-us/kachiguda/" },
    { name: "Banjara Hills - 1", path: "/contact-us/banjara-hills1/" },
    { name: "Banjara Hills - 2", path: "/contact-us/banjara-hills2/" }
];

export const departments = [
    { name: "Cardiology", path: "/specialities/cardiac-sciences" },
    { name: "Gastroenterology", path: "/specialities/gastro-sciences" },
    { name: "Neurology", path: "/specialities/neuro-sciences" },
    { name: "Robotics", path: "/specialities/robotics-science" },
    { name: "Transplant", path: "/specialities/transplant-medicine" },
    { name: "Nephrology", path: "/specialities/nephrology" },
    { name: "Urology", path: "/specialities/urology" },
    { name: "Orthopaedics", path: "/specialities/orthopaedics" },
    { name: "Mother & Child Care", path: "/specialities/mother-child-care" },
    { name: "Oncology", path: "/specialities/oncology" },
    { name: "Internal Medicine", path: "/specialities/internal-medicine" },
    { name: "Pulmonology", path: "/specialities/pulmonology" },
    { name: "ENT", path: "/specialities/ent" },
    { name: "Skin & Cosmetic care", path: "/specialities/dermatology-cosmetic-care" },
    { name: "Dental & Maxillofacial", path: "/specialities/dental-and-maxillofacial-care" },
    { name: "EYE/ Ophthalmology", path: "/specialities/eye-ophthalmology" },
    { name: "Anaesthesia & Pain management", path: "/specialities/anaesthesia-and-pain-management" },
];

export const healthConditions = [
    "Acid Reflux",
    "Arrhythmias",
    "Alzheimer's Disease",
    "Angina",
    "Atrial Fibrillation",
    "Brain tumors",
    "Benign Prostatic Hyperplasia",
    "Coronary Artery Disease",
    "Cardiomyopathy",
    "Chronic Obstructive Pulmonary Disease (COPD)",
    "Chronic Kidney Disease (CKD)",
    "Deep Vein Thrombosis",
    "Diabetes Mellitus",
    "Dementia",
    "Endocarditis",
    "Epilepsy",
    "Gallstones",
    "Gastroparesis",
    "Fatty Liver Disease",
    "Hypertension (High Blood Pressure)",
    "Hypothyroidism",
    "Parkinson’s Disease",
    "Stroke",
    "Pancreatitis"
];

export const treatmetnAndProcedures = [
    "ACL Reconstruction Surgery",
    "ASD Closure",
    "Aneurysm Clipping",
    "Adenoidectomy",
    "Bariatric Surgery",
    "Brain Tumor Surgery",
    "Carpal Tunnel Release Surgery",
    "Coronary Artery Bypass Grafting (CABG)",
    "Diabetic Foot Surgery",
    "Endometrial Ablation",
    "ERCP",
    "Appendectomy",
    "Cholecystectomy (Gallbladder Removal)",
    "Thyroidectomy",
    "Mastectomy",
    "Hernia Repair Surgery",
    "Hip Replacement Surgery",
    "Knee Replacement Surgery",
    "Laparoscopic Hysterectomy",
    "Laparoscopic Myomectomy",
    "Pacemaker Implantation",
    "Ureteroscopy with Laser Lithotripsy",
    "Percutaneous Nephrolithotomy (PCNL)",
    "Laparoscopic Ovarian Cyst Removal",
    "Varicose Vein Laser Treatment (EVLT)",
    "Hemorrhoidectomy (Piles Surgery)",
    "Functional Endoscopic Sinus Surgery (FESS)",
    "Lumbar Discectomy"
];

export const diagnosticsGuide = [
    "Coronary Angiography",
    "Colonoscopy",
    "CT Scan",
    "Complete Blood Picture(CBP)",
    "Electrocardiogram (ECG)",
    "Endoscopy",
    "Magnetic Resonance Imaging (MRI)",
    "Ultrasound (USG)",
    "Pulmonary Function Test (PFT)",
    "Liver Function Test (LFT)",
    "Complete Blood Count (CBC)",
    "Echocardiography (2D Echo)",
    "Stress Test / TMT",
    "Holter Monitoring",
    "EEG (Electroencephalogram)",
    "EMG / Nerve Conduction Study (NCS)",
    "Mammography",
    "Bone Density Scan (DEXA)",
    "HBA1c Test",
    "Kidney Function Test (KFT)",
    "Thyroid Function Test (TFT)",
    "X-Ray",
    "PSA Test (Prostate Specific Antigen)",
    "Coagulation Profile (PT/INR, APTT)",
    "Urine Routine & Microscopy",
    "Stool Examination",
    "Allergy Testing (IgE Panel)",
    "Vitamin D & B12 Levels"
];

export const symptomsGuide = [
    "Abdominal Pain",
    "Chest Pain",
    "Shortness of Breath",
    "Dizziness",
    "Severe Headache",
    "Confusion",
    "Palpitations",
    "High Fever",
    "Unexplained Weight Loss",
    "Diarrhoea",
    "Constipation",
    "Abdominal Bloating",
    "Blood in Stool",
    "Loss of Appetite",
    "Heartburn",
    "Cough",
    "Sore Throat",
    "Difficulty Breathing",
    "Weakness in Limbs",
    "Speech Difficulty",
    "Blurred Vision",
    "Seizures",
    "Back Pain",
    "Joint Pain",
    "Muscle Cramps",
    "Skin Rashes",
    "Hair Loss",
    "Swelling (Edema)",
    "Ear Pain",
    "Nasal Congestion",
    "Bleeding Gums",
    "Painful Urination"
];

export const medicineGuide = [
    "Aceclofenac",
    "Abacavir",
    "Acetaminophen (Paracetamol)",
    "Baclofen",
    "Betamethasone",
    "Budesonide",
    "Carvedilol",
    "Carbidopa",
    "Deflazacort",
    "Diclofenac",
    "Dexamethasone",
    "Amoxicillin",
    "Azithromycin",
    "Amlodipine",
    "Atorvastatin",
    "Cetirizine",
    "Clopidogrel",
    "Domperidone",
    "Esomeprazole",
    "Furosemide",
    "Gabapentin",
    "Ibuprofen",
    "Levothyroxine",
    "Metformin",
    "Metoprolol",
    "Omeprazole",
    "Pantoprazole",
    "Prednisolone",
    "Pregabalin",
    "Tramadol"
]

export const medicalTechnology = [
    "Robotic Surgery System",
    "Magnetic Resonance Imaging (MRI)",
    "CT Scan",
    "ECMO – Extracorporeal Membrane Oxygenation",
    "Neuro-Navigation System",
    "Holmium Laser (HoLEP) for Prostate",
    "High-Definition Endoscopy & ERCP System",
    "Intravascular Ultrasound (IVUS) & OCT Imaging",
    "Organ Transplant Monitoring System"
]

export const secondOpinion = [
    "ACL Reconstruction Surgery",
    "Adenoidectomy Surgery",
    "Arthroscopic Joint Surgery",
    "Bariatric Surgery",
    "Brain Tumor Surgery",
    "Breast Augmentation Surgery",
    "Carpal Tunnel Release Surgery",
    "Cerebral Aneurysm Surgery",
    "Coronary Artery Bypass Grafting (CABG)",
    "Diabetic Foot Surgery",
    "ERCP Surgery",
    "Fistula Surgery",
    "Gallbladder Stone Removal Surgery",
    "Gastric Sleeve Surgery",
    "Gynecomastia Surgery",
    "Hernia Surgery",
    "Hip Replacement Surgery",
    "Hysterectomy Surgery",
    "ICD Implantation Surgery",
    "Knee Replacement Surgery",
    "Liposuction Surgery",
    "Myomectomy Surgery",
    "Ovarian Cyst Removal Surgery",
    "Percutaneous Nephrolithotomy (PCNL)",
    "Prostate Surgery",
    "Rhinoplasty Nose Surgery",
    "Rotator Cuff Surgery",
    "Thyroidectomy Surgery",
    "TURP – Transurethral Resection of Prostate",
    "Varicose Vein Surgery"
]

export const healthPackages = [
    { name: "Whole Body Checkup", path: "/health-package/whole-body-check-up-package/" },
    { name: "Executive Health Checkup – Pro", path: "/health-package/executive-health-checkup-pro-package/" },
    { name: "Master Health Checkup", path: "/health-package/master-health-check-up-package/ " },
    { name: "Lifestyle Screen Quick Checkup", path: "/health-package/lifestyle-screen-quick-check-up-package/" },
    { name: "Executive Health Checkup", path: "/health-package/executive-health-check-up-package/" },
    { name: "General Quick Checkup", path: "/health-package/general-quick-health-check-up-package/" },
    { name: "Cardiac Health Checkup", path: "/health-package/cardiac-health-check-up-package/" },
    { name: "Gastro Health Checkup", path: "/health-package/gastro-health-check-up-package/" },
    { name: "Kidney Health Checkup", path: "/health-package/kidney-health-check-up-package/" },
    { name: "Lungs Health Checkup", path: "/health-package/lungs-health-check-up-package/" },
    { name: "Orthopedics Health Checkup", path: "/health-package/orthopedic-health-check-up-package/" }
]
